version: '2.1'
# 6/23/2017 - version 3.x does not support extends yet.
# - https://docs.docker.com/compose/extends/#extending-services
services:
  dashboard:
    build: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    environment:
      AUTHENTICATION_API_BASE_URL: "https://perry.preint.cwds.io"
      INTAKE_URL: "https://web.preint.cwds.io/intake"
      CALS_URL: "https://web.preint.cwds.io/cals"
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    volumes:
      - .:/var/www/dashboard
    tty: true
    stdin_open: true
  redis:
    image: 'redis:3.0'
    ports:
      - "6379:6379"
